language: python

python:
  - 3.5

env:
  - TRAVIS_CI=testing

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate --noinput
  - python manage.py collectstatic

script:
  - python manage.py test


deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: raviten/crispy-enigma
  bucket: bt-code-bucket
  region: ap-southeast-1
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: bt-code-bucket
  key: latest.zip
  bundle_type: zip
  application: britecore-backend
  deployment_group: britecore
  region: ap-southeast-1
  on: *2

script:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip