language: python

python:
  - 3.5

env:
  - TRAVIS_CI=testing

install:
  - pip install -r requirements.txt

before_script:
  - python code/manage.py migrate --noinput
  - python code/manage.py collectstatic

script:
  - python code/manage.py test