# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-04 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericFieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('T', 'text'), ('N', 'number'), ('D', 'date'), ('E', 'enum')], max_length=20)),
                ('ordering', models.IntegerField(default=1)),
                ('value', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False)),
                ('version', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('published', models.DateTimeField()),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_model', to='insurer.Insurer')),
            ],
        ),
        migrations.CreateModel(
            name='Validator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('>', 'greaterthan'), ('<', 'lessthan'), ('>=', 'greaterthan_or_equal'), ('<=', 'lessthan_or_equal'), ('==', 'equals'), ('!=', 'not_equals'), ('equals', 'text_equals'), ('is_one_of', 'enum_validator')], max_length=50)),
                ('value', models.TextField()),
                ('generic_field_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_type.GenericFieldType')),
            ],
        ),
        migrations.AddField(
            model_name='genericfieldtype',
            name='risk_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_type.RiskModel'),
        ),
    ]
