# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-04 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_type', '0002_remove_genericfieldtype_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validator',
            name='generic_field_type',
        ),
        migrations.AddField(
            model_name='genericfieldtype',
            name='validators',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Validator',
        ),
    ]
