# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-23 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk_type', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldtype',
            old_name='risk_model',
            new_name='risk_type',
        ),
        migrations.AlterField(
            model_name='risktype',
            name='insurer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_type', to='insurer.Insurer'),
        ),
    ]
