# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-23 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk_type', '0002_auto_20180223_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='risk',
            old_name='risk_model',
            new_name='risk_type',
        ),
        migrations.AlterField(
            model_name='risktype',
            name='insurer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_types', to='insurer.Insurer'),
        ),
    ]
